/* 
Every module must follow this ownership rule.

Section	    Purpose	                    Owner
meta	    immutable image info	    pacev3
image	    pixel data	                core / actuator
stats	    global image statistics	    stats layer
params	    controller parameters	    controller
maps	    spatial maps & masks	    controller
buffers	    temporary working arrays	controller / actuator
runtime	    stage & progress info	    pipeline

*/
export function createContext(imageData) {

    const width = imageData.width;
    const height = imageData.height;
    const totalPixels = width * height;

    return {

        meta: {
            width,
            height,
            totalPixels
        },

        image: {
            input: imageData, // ImageData
            working: {
                L: null, // Float32Array, All pixel processing happens on it
                A: null, // Float32Array
                B: null  // Float32Array
            },
            output: null // Uint8ClampedArray
        },

        stats: {}, // filled by stats layers

        params: {}, // Generated by controller's adaptiveparams layers

        maps: {}, // Generated by controller's map layers

        buffers: {}, // For intermediate calculations

        metrics: {}, // stageName: runtime(ms)

        runtime: { // Used for progress bar and debugging
            stage: "",
            progressPercent: 0,
            stages: 0,
            prevStage: ""
        }

    };
}